### ISSUE TITLE
Create the Client model and initial CRUD routes

### ISSUE THREAD

**Issue by PetitsPoissons** [PetitsPoissons/admin-patient-system#7]
- [x] Create the Client model with attributes per our E/R diagram
- [x] Create initial CRUD routes
- [x] Test routes using Insomnia

**Comment by PetitsPoissons** [comment]
Hey Sean, let me know if you can get the CRUD routes going for the Client model. Don't forget to create your own `.env` file in your root , and make sure to place into your `.gitignore` file (see instructions in the README of our repo). Best, Sandrine

**Comment by seanc0ne** [comment]
Yay!
